/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as LogicRouteImport } from './routes/logic'
import { Route as IndexRouteImport } from './routes/index'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const LogicRoute = LogicRouteImport.update({
  id: '/logic',
  path: '/logic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logic': typeof LogicRoute
  '/paper': typeof PaperRoute
  '/signals': typeof SignalsRoute
  '/tracker': typeof TrackerRoute
  '/wallets': typeof WalletsRoute
  '/api/public/hooks/compute-signals': typeof ApiPublicHooksComputeSignalsRoute
  '/api/public/hooks/paper-execute': typeof ApiPublicHooksPaperExecuteRoute
  '/api/public/hooks/refresh-whale-performance': typeof ApiPublicHooksRefreshWhalePerformanceRoute
  '/api/public/hooks/scan-wallets': typeof ApiPublicHooksScanWalletsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logic': typeof LogicRoute
  '/paper': typeof PaperRoute
  '/signals': typeof SignalsRoute
  '/tracker': typeof TrackerRoute
  '/wallets': typeof WalletsRoute
  '/api/public/hooks/compute-signals': typeof ApiPublicHooksComputeSignalsRoute
  '/api/public/hooks/paper-execute': typeof ApiPublicHooksPaperExecuteRoute
  '/api/public/hooks/refresh-whale-performance': typeof ApiPublicHooksRefreshWhalePerformanceRoute
  '/api/public/hooks/scan-wallets': typeof ApiPublicHooksScanWalletsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logic': typeof LogicRoute
  '/paper': typeof PaperRoute
  '/signals': typeof SignalsRoute
  '/tracker': typeof TrackerRoute
  '/wallets': typeof WalletsRoute
  '/api/public/hooks/compute-signals': typeof ApiPublicHooksComputeSignalsRoute
  '/api/public/hooks/paper-execute': typeof ApiPublicHooksPaperExecuteRoute
  '/api/public/hooks/refresh-whale-performance': typeof ApiPublicHooksRefreshWhalePerformanceRoute
  '/api/public/hooks/scan-wallets': typeof ApiPublicHooksScanWalletsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logic'
    | '/paper'
    | '/signals'
    | '/tracker'
    | '/wallets'
    | '/api/public/hooks/compute-signals'
    | '/api/public/hooks/paper-execute'
    | '/api/public/hooks/refresh-whale-performance'
    | '/api/public/hooks/scan-wallets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logic'
    | '/paper'
    | '/signals'
    | '/tracker'
    | '/wallets'
    | '/api/public/hooks/compute-signals'
    | '/api/public/hooks/paper-execute'
    | '/api/public/hooks/refresh-whale-performance'
    | '/api/public/hooks/scan-wallets'
  id:
    | '__root__'
    | '/'
    | '/logic'
    | '/paper'
    | '/signals'
    | '/tracker'
    | '/wallets'
    | '/api/public/hooks/compute-signals'
    | '/api/public/hooks/paper-execute'
    | '/api/public/hooks/refresh-whale-performance'
    | '/api/public/hooks/scan-wallets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogicRoute: typeof LogicRoute
  PaperRoute: typeof PaperRoute
  SignalsRoute: typeof SignalsRoute
  TrackerRoute: typeof TrackerRoute
  WalletsRoute: typeof WalletsRoute
  ApiPublicHooksComputeSignalsRoute: typeof ApiPublicHooksComputeSignalsRoute
  ApiPublicHooksPaperExecuteRoute: typeof ApiPublicHooksPaperExecuteRoute
  ApiPublicHooksRefreshWhalePerformanceRoute: typeof ApiPublicHooksRefreshWhalePerformanceRoute
  ApiPublicHooksScanWalletsRoute: typeof ApiPublicHooksScanWalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logic': {
      id: '/logic'
      path: '/logic'
      fullPath: '/logic'
      preLoaderRoute: typeof LogicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-wallets': {
      id: '/api/public/hooks/scan-wallets'
      path: '/api/public/hooks/scan-wallets'
      fullPath: '/api/public/hooks/scan-wallets'
      preLoaderRoute: typeof ApiPublicHooksScanWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-whale-performance': {
      id: '/api/public/hooks/refresh-whale-performance'
      path: '/api/public/hooks/refresh-whale-performance'
      fullPath: '/api/public/hooks/refresh-whale-performance'
      preLoaderRoute: typeof ApiPublicHooksRefreshWhalePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/paper-execute': {
      id: '/api/public/hooks/paper-execute'
      path: '/api/public/hooks/paper-execute'
      fullPath: '/api/public/hooks/paper-execute'
      preLoaderRoute: typeof ApiPublicHooksPaperExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/compute-signals': {
      id: '/api/public/hooks/compute-signals'
      path: '/api/public/hooks/compute-signals'
      fullPath: '/api/public/hooks/compute-signals'
      preLoaderRoute: typeof ApiPublicHooksComputeSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogicRoute: LogicRoute,
  PaperRoute: PaperRoute,
  SignalsRoute: SignalsRoute,
  TrackerRoute: TrackerRoute,
  WalletsRoute: WalletsRoute,
  ApiPublicHooksComputeSignalsRoute: ApiPublicHooksComputeSignalsRoute,
  ApiPublicHooksPaperExecuteRoute: ApiPublicHooksPaperExecuteRoute,
  ApiPublicHooksRefreshWhalePerformanceRoute:
    ApiPublicHooksRefreshWhalePerformanceRoute,
  ApiPublicHooksScanWalletsRoute: ApiPublicHooksScanWalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
