ALTER TABLE public.real_bot_config
  ADD COLUMN IF NOT EXISTS last_run_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_run_opened INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_run_closed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_run_skipped INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_run_status TEXT,
  ADD COLUMN IF NOT EXISTS last_run_error TEXT;